### ISSUE TITLE
Introdução a UnB Coin 

### ISSUE THREAD

**Issue by SomeGoodGuy** [oteomoura/lawBlockchainClass#10]
# Introdução a **UnB Coin**
![unbcoin](https://user-images.githubusercontent.com/37467453/37638289-d5431f0e-2bea-11e8-810a-c5131e214a2f.jpg)
## O que é?

A **UnB Coin** é um token que funciona na rede Ethereum (ERC20) e tem por objetivo de modernizar o ecossistema da UnB, deixando-o mais inovador, seguro e integrador. 

## Para que serve? 

 - Auxiliar os alunos em seus gastos cotidianos com a UnB, incluindo lanches, xerox e compra de material, tudo isso de forma rápida e prática graças a tecnologia _blockchain_.
 - Os alunos poderão utilizar seus tokens em projetos de _Crowd Funding_ para melhorar a vida dos estudantes. 
 - Os estabelecimentos comerciais da UnB poderão utilizar a plataforma como _Cartão Fidelidade_, oferecendo descontos e promoções para seus consumidores.
 - Além disso, os alunos poderão ter acesso a uma plataforma de integração social, utilizando o _Sistema de Assinatura Digital_(DSA) da plataforma.
 - Todas as ações poderão ser feitas através do _smartphone_, computador ou em qualquer terminal da UnB. O sistema também tem suporte para operações manuais usando uma _Paper Wallet_.
 - Também é possível utilizar a tecnologia como controle de acesso a anfiteatros, chamadas e compra e venda de produtos em eventos que ocorram na UnB.
 - O sistema também possibilita a construção de um sistema de votação prático, rápido e seguro, ideal para votações de DCE e outras pautas.

## Como será implementada?

Cada aluno possui um número de cadastro que será vinculado a um banco de dados da UnB. Os dados do aluno não podem ser acessados publicamente, entretanto é possível confirmar se um endereço pertence a um aluno da UnB ou não publicamente. 

## Como faço para adquirir UnB Coins? 

Você poderá adquirir UnB Coins em quaisquer quiosque habilitado na UnB, além de comprar através do cartão de crédito ou outras criptomoedas dentro de uma plataforma própria. Não existem taxas para os alunos da UnB, entretanto os estabelecimentos comerciais aceitarão receber as UnB Coins por uma taxa mais baixa que a das maquininhas de cartão de crédito convencionais. 

**É importante destacar que o aluno não precisa pagar para poder usar a plataforma.** Os custos são contabilizados sempre que algum interessado (seja a UnB ou um particular) quiser incluir seu projeto na plataforma. Os valores são pequenos, e servem somente para não deixar os desenvolvedores morrerm de fome. 

## Não conheço nada sobre criptomoedas. Vai ser difícil usar? 

Se você consegue usar o WhatsApp e seu aplicativo do banco no celular, com certeza vai ser moleza para você! 

## Esse projeto é uma piada? 

Era, só que ai eu fui vendo o potencial que uma plataforma dessas tinha e eu comecei a levar o projeto a sério. Na pior hipótese dá para aprender tudo sobre criptomoedas do modo mais prático possível. Então eu te pergunto: _por que não?_

## Roadmap

- [x] Criar uma identidade visual maneira com fundo da UnB.
- [x] Registrar o _SmartContract_ na rede do Ethereum.
- [x] Fazer um _white paper_ no Git da turma que aparentemente só eu acesso. 
- [x] Esperar até que Teo ou o Ale vejam e levem a piada para a turma.
- [ ] Ver se existe um grupo de gente doida o bastante para entrar no projeto comigo. 
- [ ] Montar um material para construir a equipe de desenvolvimento.
- [ ] Iniciar desenvolvimento de um MVP + BP.
- [ ] Acionar meus contatos na mídia para que o projeto ganhe visibilidade.
- [ ] Iniciar publicidade para entidades que vão bancar ($$) o projeto.
- [ ] Criar grupos de oração para pedir investidores. Adicionar custo do incenso ao _business plan_.
